#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,4,73,41,43,55,58&i=1,2,3,4,15,16,17,31,32,33&v=4,5,-1,255,27,26,25,35,33,32 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_SSD1322

#define ENC2_BTNR			34
#define ENC2_BTNL			33
#define ENC2_BTNB			35


// pocet sekund na automaticke potvrzeni skladby z playlistu
// to je moje uprava v display.cpp a timekeeper.cpp
#define AUTOCOMMIT	2

// aby nebyl nazev stanice invertovany
#define DSP_INVERT_TITLE 0

#endif

